/**
 * 完整卡牌数据库 (95种卡牌)
 * 规则依据: 完善的游戏规则.md R8.0
 * 
 * 卡牌分类:
 * - 进攻方卡牌 (ATK001-048): 48张
 * - 防御方卡牌 (DEF001-047): 47张
 */

// ============================================
// 本地类型定义
// ============================================

export type CardType = 'attack' | 'defense' | 'support';
export type CardRarity = 'common' | 'rare' | 'epic' | 'legendary';
export type CardFaction = 'attack' | 'defense';

export interface CardResources {
  compute: number;
  funds: number;
  information: number;
}

export interface CardEffect {
  type: string;
  value: number;
  resourceType?: string;
  immunityType?: string;
}

export interface Card {
  id: string;
  code: string;
  name: string;
  type: CardType;
  faction: CardFaction;
  rarity: CardRarity;
  cost: Partial<CardResources>;
  description: string;
  effects: CardEffect[];
  target: 'self' | 'opponent' | 'all';
  isAura?: boolean;
  winCondition?: {
    type: string;
    threshold: number;
  };
}

// ============================================
// 进攻方卡牌 (ATK001-048)
// ============================================

export const ATTACKER_CARDS: Card[] = [
  // T0 基础卡 (ATK001-008)
  {
    id: 'ATK001',
    code: 'ATK001',
    name: '端口扫描',
    type: 'attack',
    faction: 'attack',
    rarity: 'common',
    cost: { compute: 1, funds: 0, information: 1 },
    description: '对目标系统进行端口扫描，渗透+1',
    effects: [{ type: 'infiltration', value: 1 }],
    target: 'opponent',
  },
  {
    id: 'ATK002',
    code: 'ATK002',
    name: '钓鱼邮件',
    type: 'attack',
    faction: 'attack',
    rarity: 'common',
    cost: { compute: 0, funds: 1, information: 1 },
    description: '发送钓鱼邮件获取凭证，渗透+1',
    effects: [{ type: 'infiltration', value: 1 }],
    target: 'opponent',
  },
  {
    id: 'ATK003',
    code: 'ATK003',
    name: '社工库查询',
    type: 'attack',
    faction: 'attack',
    rarity: 'common',
    cost: { compute: 0, funds: 0, information: 2 },
    description: '查询社工库获取信息，渗透+1',
    effects: [{ type: 'infiltration', value: 1 }],
    target: 'opponent',
  },
  {
    id: 'ATK004',
    code: 'ATK004',
    name: '弱口令爆破',
    type: 'attack',
    faction: 'attack',
    rarity: 'common',
    cost: { compute: 2, funds: 0, information: 0 },
    description: '暴力破解弱口令，渗透+1',
    effects: [{ type: 'infiltration', value: 1 }],
    target: 'opponent',
  },
  {
    id: 'ATK005',
    code: 'ATK005',
    name: '信息收集',
    type: 'support',
    faction: 'attack',
    rarity: 'common',
    cost: { compute: 0, funds: 0, information: 1 },
    description: '收集目标信息，抽1张卡',
    effects: [{ type: 'draw', value: 1 }],
    target: 'self',
  },
  {
    id: 'ATK006',
    code: 'ATK006',
    name: '资金筹措',
    type: 'support',
    faction: 'attack',
    rarity: 'common',
    cost: { compute: 0, funds: 0, information: 0 },
    description: '筹集攻击资金，资金+2',
    effects: [{ type: 'resource', value: 2, resourceType: 'funds' }],
    target: 'self',
  },
  {
    id: 'ATK007',
    code: 'ATK007',
    name: '算力租赁',
    type: 'support',
    faction: 'attack',
    rarity: 'common',
    cost: { compute: 0, funds: 2, information: 0 },
    description: '租赁云计算资源，算力+2',
    effects: [{ type: 'resource', value: 2, resourceType: 'compute' }],
    target: 'self',
  },
  {
    id: 'ATK008',
    code: 'ATK008',
    name: '暗网交易',
    type: 'support',
    faction: 'attack',
    rarity: 'common',
    cost: { compute: 0, funds: 1, information: 1 },
    description: '在暗网购买漏洞信息，信息+2',
    effects: [{ type: 'resource', value: 2, resourceType: 'information' }],
    target: 'self',
  },

  // T1 进阶卡 (ATK009-016)
  {
    id: 'ATK009',
    code: 'ATK009',
    name: 'SQL注入',
    type: 'attack',
    faction: 'attack',
    rarity: 'rare',
    cost: { compute: 2, funds: 0, information: 1 },
    description: '利用SQL注入漏洞，渗透+2',
    effects: [{ type: 'infiltration', value: 2 }],
    target: 'opponent',
  },
  {
    id: 'ATK010',
    code: 'ATK010',
    name: 'XSS攻击',
    type: 'attack',
    faction: 'attack',
    rarity: 'rare',
    cost: { compute: 1, funds: 0, information: 2 },
    description: '跨站脚本攻击，渗透+2',
    effects: [{ type: 'infiltration', value: 2 }],
    target: 'opponent',
  },
  {
    id: 'ATK011',
    code: 'ATK011',
    name: 'CSRF利用',
    type: 'attack',
    faction: 'attack',
    rarity: 'rare',
    cost: { compute: 2, funds: 0, information: 1 },
    description: '跨站请求伪造攻击，渗透+2',
    effects: [{ type: 'infiltration', value: 2 }],
    target: 'opponent',
  },
  {
    id: 'ATK012',
    code: 'ATK012',
    name: '文件上传漏洞',
    type: 'attack',
    faction: 'attack',
    rarity: 'rare',
    cost: { compute: 2, funds: 0, information: 1 },
    description: '利用文件上传漏洞植入后门，渗透+2',
    effects: [{ type: 'infiltration', value: 2 }],
    target: 'opponent',
  },
  {
    id: 'ATK013',
    code: 'ATK013',
    name: '命令注入',
    type: 'attack',
    faction: 'attack',
    rarity: 'rare',
    cost: { compute: 3, funds: 0, information: 0 },
    description: '远程命令执行，渗透+2',
    effects: [{ type: 'infiltration', value: 2 }],
    target: 'opponent',
  },
  {
    id: 'ATK014',
    code: 'ATK014',
    name: '逻辑漏洞利用',
    type: 'attack',
    faction: 'attack',
    rarity: 'rare',
    cost: { compute: 1, funds: 0, information: 2 },
    description: '利用业务逻辑漏洞，渗透+2',
    effects: [{ type: 'infiltration', value: 2 }],
    target: 'opponent',
  },
  {
    id: 'ATK015',
    code: 'ATK015',
    name: '权限提升',
    type: 'support',
    faction: 'attack',
    rarity: 'rare',
    cost: { compute: 2, funds: 1, information: 1 },
    description: '提升系统权限，渗透+1，抽1张卡',
    effects: [{ type: 'infiltration', value: 1 }, { type: 'draw', value: 1 }],
    target: 'self',
  },
  {
    id: 'ATK016',
    code: 'ATK016',
    name: '横向移动',
    type: 'attack',
    faction: 'attack',
    rarity: 'rare',
    cost: { compute: 2, funds: 1, information: 1 },
    description: '在内网横向移动，渗透+2',
    effects: [{ type: 'infiltration', value: 2 }],
    target: 'opponent',
  },

  // T2 高级卡 (ATK017-024)
  {
    id: 'ATK017',
    code: 'ATK017',
    name: '零日漏洞',
    type: 'attack',
    faction: 'attack',
    rarity: 'epic',
    cost: { compute: 3, funds: 2, information: 2 },
    description: '利用未公开的零日漏洞，渗透+3',
    effects: [{ type: 'infiltration', value: 3 }],
    target: 'opponent',
  },
  {
    id: 'ATK018',
    code: 'ATK018',
    name: '供应链攻击',
    type: 'attack',
    faction: 'attack',
    rarity: 'epic',
    cost: { compute: 2, funds: 3, information: 2 },
    description: '攻击软件供应链，渗透+3',
    effects: [{ type: 'infiltration', value: 3 }],
    target: 'opponent',
  },
  {
    id: 'ATK019',
    code: 'ATK019',
    name: 'APT植入',
    type: 'attack',
    faction: 'attack',
    rarity: 'epic',
    cost: { compute: 3, funds: 2, information: 3 },
    description: '植入高级持续性威胁，渗透+3',
    effects: [{ type: 'infiltration', value: 3 }],
    target: 'opponent',
  },
  {
    id: 'ATK020',
    code: 'ATK020',
    name: '勒索软件',
    type: 'attack',
    faction: 'attack',
    rarity: 'epic',
    cost: { compute: 3, funds: 1, information: 2 },
    description: '部署勒索软件，渗透+3，对方资金-2',
    effects: [{ type: 'infiltration', value: 3 }, { type: 'opponent_resource', value: -2, resourceType: 'funds' }],
    target: 'opponent',
  },
  {
    id: 'ATK021',
    code: 'ATK021',
    name: '数据窃取',
    type: 'attack',
    faction: 'attack',
    rarity: 'epic',
    cost: { compute: 2, funds: 1, information: 3 },
    description: '窃取敏感数据，渗透+2，信息+2',
    effects: [{ type: 'infiltration', value: 2 }, { type: 'resource', value: 2, resourceType: 'information' }],
    target: 'opponent',
  },
  {
    id: 'ATK022',
    code: 'ATK022',
    name: '内网渗透',
    type: 'attack',
    faction: 'attack',
    rarity: 'epic',
    cost: { compute: 3, funds: 1, information: 2 },
    description: '深度渗透内网，渗透+3',
    effects: [{ type: 'infiltration', value: 3 }],
    target: 'opponent',
  },
  {
    id: 'ATK023',
    code: 'ATK023',
    name: '持久化后门',
    type: 'support',
    faction: 'attack',
    rarity: 'epic',
    cost: { compute: 3, funds: 2, information: 1 },
    description: '建立持久化后门，每回合渗透+1',
    effects: [{ type: 'infiltration_per_turn', value: 1 }],
    target: 'self',
    isAura: true,
  },
  {
    id: 'ATK024',
    code: 'ATK024',
    name: 'C2通信',
    type: 'support',
    faction: 'attack',
    rarity: 'epic',
    cost: { compute: 2, funds: 2, information: 2 },
    description: '建立命令控制通道，抽2张卡',
    effects: [{ type: 'draw', value: 2 }],
    target: 'self',
  },

  // T3 专家卡 (ATK025-032)
  {
    id: 'ATK025',
    code: 'ATK025',
    name: '国家级工具',
    type: 'attack',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 4, funds: 3, information: 3 },
    description: '使用国家级攻击工具，渗透+4',
    effects: [{ type: 'infiltration', value: 4 }],
    target: 'opponent',
  },
  {
    id: 'ATK026',
    code: 'ATK026',
    name: '物理渗透',
    type: 'attack',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 2, funds: 4, information: 3 },
    description: '物理访问目标设施，渗透+4',
    effects: [{ type: 'infiltration', value: 4 }],
    target: 'opponent',
  },
  {
    id: 'ATK027',
    code: 'ATK027',
    name: '社会工程学',
    type: 'attack',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 1, funds: 3, information: 4 },
    description: '高级社会工程攻击，渗透+4',
    effects: [{ type: 'infiltration', value: 4 }],
    target: 'opponent',
  },
  {
    id: 'ATK028',
    code: 'ATK028',
    name: '水坑攻击',
    type: 'attack',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 3, funds: 3, information: 3 },
    description: '水坑式攻击，渗透+4',
    effects: [{ type: 'infiltration', value: 4 }],
    target: 'opponent',
  },
  {
    id: 'ATK029',
    code: 'ATK029',
    name: '域控接管',
    type: 'attack',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 4, funds: 2, information: 3 },
    description: '接管域控制器，渗透+4',
    effects: [{ type: 'infiltration', value: 4 }],
    target: 'opponent',
  },
  {
    id: 'ATK030',
    code: 'ATK030',
    name: '证书窃取',
    type: 'attack',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 3, funds: 2, information: 4 },
    description: '窃取数字证书，渗透+4',
    effects: [{ type: 'infiltration', value: 4 }],
    target: 'opponent',
  },
  {
    id: 'ATK031',
    code: 'ATK031',
    name: '影子管理员',
    type: 'support',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 4, funds: 3, information: 2 },
    description: '创建隐藏管理员账户，渗透+2，每回合渗透+1',
    effects: [{ type: 'infiltration', value: 2 }, { type: 'infiltration_per_turn', value: 1 }],
    target: 'self',
    isAura: true,
  },
  {
    id: 'ATK032',
    code: 'ATK032',
    name: '数据加密勒索',
    type: 'attack',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 4, funds: 3, information: 2 },
    description: '加密核心数据勒索，渗透+4，对方所有资源-2',
    effects: [
      { type: 'infiltration', value: 4 },
      { type: 'opponent_resource', value: -2, resourceType: 'compute' },
      { type: 'opponent_resource', value: -2, resourceType: 'funds' },
      { type: 'opponent_resource', value: -2, resourceType: 'information' },
    ],
    target: 'opponent',
  },

  // T4 大师卡 (ATK033-040)
  {
    id: 'ATK033',
    code: 'ATK033',
    name: '核设施渗透',
    type: 'attack',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 5, funds: 4, information: 4 },
    description: '渗透关键核设施，渗透+5',
    effects: [{ type: 'infiltration', value: 5 }],
    target: 'opponent',
  },
  {
    id: 'ATK034',
    code: 'ATK034',
    name: '金融系统入侵',
    type: 'attack',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 4, funds: 5, information: 4 },
    description: '入侵金融核心系统，渗透+5，获得资金+5',
    effects: [{ type: 'infiltration', value: 5 }, { type: 'resource', value: 5, resourceType: 'funds' }],
    target: 'opponent',
  },
  {
    id: 'ATK035',
    code: 'ATK035',
    name: '电网攻击',
    type: 'attack',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 5, funds: 3, information: 4 },
    description: '攻击电力基础设施，渗透+5',
    effects: [{ type: 'infiltration', value: 5 }],
    target: 'opponent',
  },
  {
    id: 'ATK036',
    code: 'ATK036',
    name: '卫星通信劫持',
    type: 'attack',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 5, funds: 4, information: 4 },
    description: '劫持卫星通信链路，渗透+5',
    effects: [{ type: 'infiltration', value: 5 }],
    target: 'opponent',
  },
  {
    id: 'ATK037',
    code: 'ATK037',
    name: '量子计算破解',
    type: 'attack',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 6, funds: 3, information: 4 },
    description: '使用量子计算破解加密，渗透+5',
    effects: [{ type: 'infiltration', value: 5 }],
    target: 'opponent',
  },
  {
    id: 'ATK038',
    code: 'ATK038',
    name: 'AI深度伪造',
    type: 'attack',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 4, funds: 4, information: 5 },
    description: '使用AI生成深度伪造内容，渗透+5',
    effects: [{ type: 'infiltration', value: 5 }],
    target: 'opponent',
  },
  {
    id: 'ATK039',
    code: 'ATK039',
    name: '区块链攻击',
    type: 'attack',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 5, funds: 5, information: 3 },
    description: '攻击区块链网络，渗透+5',
    effects: [{ type: 'infiltration', value: 5 }],
    target: 'opponent',
  },
  {
    id: 'ATK040',
    code: 'ATK040',
    name: '智能合约漏洞',
    type: 'attack',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 4, funds: 4, information: 4 },
    description: '利用智能合约漏洞，渗透+5，获得资金+3',
    effects: [{ type: 'infiltration', value: 5 }, { type: 'resource', value: 3, resourceType: 'funds' }],
    target: 'opponent',
  },

  // T5 传奇卡 (ATK041-048)
  {
    id: 'ATK041',
    code: 'ATK041',
    name: '全球网络瘫痪',
    type: 'attack',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 6, funds: 5, information: 5 },
    description: '发动全球性网络攻击，渗透+6',
    effects: [{ type: 'infiltration', value: 6 }],
    target: 'opponent',
  },
  {
    id: 'ATK042',
    code: 'ATK042',
    name: '国家级基础设施',
    type: 'attack',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 5, funds: 6, information: 5 },
    description: '控制国家级关键基础设施，渗透+6',
    effects: [{ type: 'infiltration', value: 6 }],
    target: 'opponent',
  },
  {
    id: 'ATK043',
    code: 'ATK043',
    name: '军事系统入侵',
    type: 'attack',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 6, funds: 4, information: 6 },
    description: '入侵军事指挥系统，渗透+6',
    effects: [{ type: 'infiltration', value: 6 }],
    target: 'opponent',
  },
  {
    id: 'ATK044',
    code: 'ATK044',
    name: '太空系统攻击',
    type: 'attack',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 6, funds: 5, information: 5 },
    description: '攻击太空系统，渗透+6',
    effects: [{ type: 'infiltration', value: 6 }],
    target: 'opponent',
  },
  {
    id: 'ATK045',
    code: 'ATK045',
    name: 'AI自主攻击',
    type: 'attack',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 6, funds: 5, information: 6 },
    description: '释放自主AI攻击系统，渗透+6',
    effects: [{ type: 'infiltration', value: 6 }],
    target: 'opponent',
  },
  {
    id: 'ATK046',
    code: 'ATK046',
    name: '数字核武器',
    type: 'attack',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 7, funds: 5, information: 5 },
    description: '部署数字核武器级攻击，渗透+7',
    effects: [{ type: 'infiltration', value: 7 }],
    target: 'opponent',
  },
  {
    id: 'ATK047',
    code: 'ATK047',
    name: '终极后门',
    type: 'support',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 5, funds: 5, information: 5 },
    description: '植入不可检测的终极后门，每回合渗透+2',
    effects: [{ type: 'infiltration_per_turn', value: 2 }],
    target: 'self',
    isAura: true,
  },
  {
    id: 'ATK048',
    code: 'ATK048',
    name: '网络末日',
    type: 'attack',
    faction: 'attack',
    rarity: 'legendary',
    cost: { compute: 8, funds: 6, information: 6 },
    description: '引发网络末日级事件，直接获得胜利',
    effects: [{ type: 'win', value: 1 }],
    target: 'opponent',
    winCondition: { type: 'immediate_win', threshold: 100 },
  },
];

// ============================================
// 防御方卡牌 (DEF001-047)
// ============================================

export const DEFENDER_CARDS: Card[] = [
  // T0 基础卡 (DEF001-008)
  {
    id: 'DEF001',
    code: 'DEF001',
    name: '防火墙部署',
    type: 'defense',
    faction: 'defense',
    rarity: 'common',
    cost: { compute: 1, funds: 0, information: 1 },
    description: '部署基础防火墙，安全+1',
    effects: [{ type: 'safety', value: 1 }],
    target: 'self',
  },
  {
    id: 'DEF002',
    code: 'DEF002',
    name: '入侵检测',
    type: 'defense',
    faction: 'defense',
    rarity: 'common',
    cost: { compute: 1, funds: 1, information: 0 },
    description: '部署IDS系统，安全+1',
    effects: [{ type: 'safety', value: 1 }],
    target: 'self',
  },
  {
    id: 'DEF003',
    code: 'DEF003',
    name: '日志审计',
    type: 'defense',
    faction: 'defense',
    rarity: 'common',
    cost: { compute: 0, funds: 0, information: 2 },
    description: '审计系统日志，安全+1',
    effects: [{ type: 'safety', value: 1 }],
    target: 'self',
  },
  {
    id: 'DEF004',
    code: 'DEF004',
    name: '访问控制',
    type: 'defense',
    faction: 'defense',
    rarity: 'common',
    cost: { compute: 2, funds: 0, information: 0 },
    description: '强化访问控制，安全+1',
    effects: [{ type: 'safety', value: 1 }],
    target: 'self',
  },
  {
    id: 'DEF005',
    code: 'DEF005',
    name: '安全培训',
    type: 'support',
    faction: 'defense',
    rarity: 'common',
    cost: { compute: 0, funds: 1, information: 1 },
    description: '员工安全意识培训，抽1张卡',
    effects: [{ type: 'draw', value: 1 }],
    target: 'self',
  },
  {
    id: 'DEF006',
    code: 'DEF006',
    name: '安全预算',
    type: 'support',
    faction: 'defense',
    rarity: 'common',
    cost: { compute: 0, funds: 0, information: 0 },
    description: '申请安全预算，资金+2',
    effects: [{ type: 'resource', value: 2, resourceType: 'funds' }],
    target: 'self',
  },
  {
    id: 'DEF007',
    code: 'DEF007',
    name: '安全工具',
    type: 'support',
    faction: 'defense',
    rarity: 'common',
    cost: { compute: 0, funds: 2, information: 0 },
    description: '采购安全工具，算力+2',
    effects: [{ type: 'resource', value: 2, resourceType: 'compute' }],
    target: 'self',
  },
  {
    id: 'DEF008',
    code: 'DEF008',
    name: '威胁情报',
    type: 'support',
    faction: 'defense',
    rarity: 'common',
    cost: { compute: 0, funds: 1, information: 1 },
    description: '获取威胁情报，信息+2',
    effects: [{ type: 'resource', value: 2, resourceType: 'information' }],
    target: 'self',
  },

  // T1 进阶卡 (DEF009-016)
  {
    id: 'DEF009',
    code: 'DEF009',
    name: 'WAF部署',
    type: 'defense',
    faction: 'defense',
    rarity: 'rare',
    cost: { compute: 2, funds: 1, information: 0 },
    description: '部署Web应用防火墙，安全+2',
    effects: [{ type: 'safety', value: 2 }],
    target: 'self',
  },
  {
    id: 'DEF010',
    code: 'DEF010',
    name: 'SIEM系统',
    type: 'defense',
    faction: 'defense',
    rarity: 'rare',
    cost: { compute: 2, funds: 1, information: 1 },
    description: '部署安全信息与事件管理，安全+2',
    effects: [{ type: 'safety', value: 2 }],
    target: 'self',
  },
  {
    id: 'DEF011',
    code: 'DEF011',
    name: '端点保护',
    type: 'defense',
    faction: 'defense',
    rarity: 'rare',
    cost: { compute: 2, funds: 0, information: 1 },
    description: '部署EDR端点保护，安全+2',
    effects: [{ type: 'safety', value: 2 }],
    target: 'self',
  },
  {
    id: 'DEF012',
    code: 'DEF012',
    name: '网络分段',
    type: 'defense',
    faction: 'defense',
    rarity: 'rare',
    cost: { compute: 3, funds: 0, information: 0 },
    description: '实施网络分段隔离，安全+2',
    effects: [{ type: 'safety', value: 2 }],
    target: 'self',
  },
  {
    id: 'DEF013',
    code: 'DEF013',
    name: '蜜罐系统',
    type: 'defense',
    faction: 'defense',
    rarity: 'rare',
    cost: { compute: 2, funds: 1, information: 1 },
    description: '部署蜜罐诱捕攻击者，安全+2，信息+1',
    effects: [{ type: 'safety', value: 2 }, { type: 'resource', value: 1, resourceType: 'information' }],
    target: 'self',
  },
  {
    id: 'DEF014',
    code: 'DEF014',
    name: '漏洞扫描',
    type: 'defense',
    faction: 'defense',
    rarity: 'rare',
    cost: { compute: 1, funds: 1, information: 1 },
    description: '扫描系统漏洞，安全+2',
    effects: [{ type: 'safety', value: 2 }],
    target: 'self',
  },
  {
    id: 'DEF015',
    code: 'DEF015',
    name: '补丁管理',
    type: 'support',
    faction: 'defense',
    rarity: 'rare',
    cost: { compute: 2, funds: 1, information: 0 },
    description: '及时更新安全补丁，安全+1，抽1张卡',
    effects: [{ type: 'safety', value: 1 }, { type: 'draw', value: 1 }],
    target: 'self',
  },
  {
    id: 'DEF016',
    code: 'DEF016',
    name: '应急响应',
    type: 'defense',
    faction: 'defense',
    rarity: 'rare',
    cost: { compute: 2, funds: 1, information: 1 },
    description: '启动应急响应流程，安全+2',
    effects: [{ type: 'safety', value: 2 }],
    target: 'self',
  },

  // T2 高级卡 (DEF017-024)
  {
    id: 'DEF017',
    code: 'DEF017',
    name: '零日防护',
    type: 'defense',
    faction: 'defense',
    rarity: 'epic',
    cost: { compute: 3, funds: 2, information: 2 },
    description: '部署零日漏洞防护，安全+3',
    effects: [{ type: 'safety', value: 3 }],
    target: 'self',
  },
  {
    id: 'DEF018',
    code: 'DEF018',
    name: '供应链安全',
    type: 'defense',
    faction: 'defense',
    rarity: 'epic',
    cost: { compute: 2, funds: 3, information: 2 },
    description: '强化供应链安全，安全+3',
    effects: [{ type: 'safety', value: 3 }],
    target: 'self',
  },
  {
    id: 'DEF019',
    code: 'DEF019',
    name: 'APT检测',
    type: 'defense',
    faction: 'defense',
    rarity: 'epic',
    cost: { compute: 3, funds: 2, information: 3 },
    description: '检测高级持续性威胁，安全+3',
    effects: [{ type: 'safety', value: 3 }],
    target: 'self',
  },
  {
    id: 'DEF020',
    code: 'DEF020',
    name: '勒索防护',
    type: 'defense',
    faction: 'defense',
    rarity: 'epic',
    cost: { compute: 3, funds: 2, information: 2 },
    description: '部署勒索软件防护，安全+3',
    effects: [{ type: 'safety', value: 3 }],
    target: 'self',
  },
  {
    id: 'DEF021',
    code: 'DEF021',
    name: '数据防泄漏',
    type: 'defense',
    faction: 'defense',
    rarity: 'epic',
    cost: { compute: 2, funds: 2, information: 3 },
    description: '部署DLP数据防泄漏，安全+3',
    effects: [{ type: 'safety', value: 3 }],
    target: 'self',
  },
  {
    id: 'DEF022',
    code: 'DEF022',
    name: '内网监控',
    type: 'defense',
    faction: 'defense',
    rarity: 'epic',
    cost: { compute: 3, funds: 1, information: 2 },
    description: '强化内网流量监控，安全+3',
    effects: [{ type: 'safety', value: 3 }],
    target: 'self',
  },
  {
    id: 'DEF023',
    code: 'DEF023',
    name: '威胁狩猎',
    type: 'support',
    faction: 'defense',
    rarity: 'epic',
    cost: { compute: 3, funds: 2, information: 2 },
    description: '主动威胁狩猎，每回合安全+1',
    effects: [{ type: 'safety_per_turn', value: 1 }],
    target: 'self',
    isAura: true,
  },
  {
    id: 'DEF024',
    code: 'DEF024',
    name: '安全运营中心',
    type: 'support',
    faction: 'defense',
    rarity: 'epic',
    cost: { compute: 2, funds: 2, information: 2 },
    description: '建立SOC安全运营中心，抽2张卡',
    effects: [{ type: 'draw', value: 2 }],
    target: 'self',
  },

  // T3 专家卡 (DEF025-032)
  {
    id: 'DEF025',
    code: 'DEF025',
    name: '国家级防御',
    type: 'defense',
    faction: 'defense',
    rarity: 'legendary',
    cost: { compute: 4, funds: 3, information: 3 },
    description: '部署国家级防御系统，安全+4',
    effects: [{ type: 'safety', value: 4 }],
    target: 'self',
  },
  {
    id: 'DEF026',
    code: 'DEF026',
    name: '物理安全',
    type: 'defense',
    faction: 'defense',
    rarity: 'legendary',
    cost: { compute: 2, funds: 4, information: 3 },
    description: '强化物理安全防护，安全+4',
    effects: [{ type: 'safety', value: 4 }],
    target: 'self',
  },
  {
    id: 'DEF027',
    code: 'DEF027',
    name: '安全意识',
    type: 'defense',
    faction: 'defense',
    rarity: 'legendary',
    cost: { compute: 1, funds: 3, information: 4 },
    description: '全员安全意识提升，安全+4',
    effects: [{ type: 'safety', value: 4 }],
    target: 'self',
  },
  {
    id: 'DEF028',
    code: 'DEF028',
    name: '水坑防护',
    type: 'defense',
    faction: 'defense',
    rarity: 'legendary',
    cost: { compute: 3, funds: 3, information: 3 },
    description: '防护水坑攻击，安全+4',
    effects: [{ type: 'safety', value: 4 }],
    target: 'self',
  },
  {
    id: 'DEF029',
    code: 'DEF029',
    name: '域控加固',
    type: 'defense',
    faction: 'defense',
    rarity: 'legendary',
    cost: { compute: 4, funds: 2, information: 3 },
    description: '加固域控制器，安全+4',
    effects: [{ type: 'safety', value: 4 }],
    target: 'self',
  },
  {
    id: 'DEF030',
    code: 'DEF030',
    name: '证书管理',
    type: 'defense',
    faction: 'defense',
    rarity: 'legendary',
    cost: { compute: 3, funds: 2, information: 4 },
    description: '强化证书管理，安全+4',
    effects: [{ type: 'safety', value: 4 }],
    target: 'self',
  },
  {
    id: 'DEF031',
    code: 'DEF031',
    name: '特权管理',
    type: 'support',
    faction: 'defense',
    rarity: 'legendary',
    cost: { compute: 4, funds: 3, information: 2 },
    description: '实施特权访问管理，安全+2，每回合安全+1',
    effects: [{ type: 'safety', value: 2 }, { type: 'safety_per_turn', value: 1 }],
    target: 'self',
    isAura: true,
  },
  {
    id: 'DEF032',
    code: 'DEF032',
    name: '数据备份',
    type: 'defense',
    faction: 'defense',
    rarity: 'legendary',
    cost: { compute: 3, funds: 3, information: 2 },
    description: '完善数据备份策略，安全+4，免疫一次渗透攻击',
    effects: [{ type: 'safety', value: 4 }, { type: 'immunity', value: 1, immunityType: 'infiltration' }],
    target: 'self',
  },

  // T4 大师卡 (DEF033-039)
  {
    id: 'DEF033',
    code: 'DEF033',
    name: '核设施防护',
    type: 'defense',
    faction: 'defense',
    rarity: 'legendary',
    cost: { compute: 5, funds: 4, information: 4 },
    description: '核设施级安全防护，安全+5',
    effects: [{ type: 'safety', value: 5 }],
    target: 'self',
  },
  {
    id: 'DEF034',
    code: 'DEF034',
    name: '金融系统防护',
    type: 'defense',
    faction: 'defense',
    rarity: 'legendary',
    cost: { compute: 4, funds: 5, information: 4 },
    description: '金融级安全防护，安全+5',
    effects: [{ type: 'safety', value: 5 }],
    target: 'self',
  },
  {
    id: 'DEF035',
    code: 'DEF035',
    name: '电网防护',
    type: 'defense',
    faction: 'defense',
    rarity: 'legendary',
    cost: { compute: 5, funds: 3, information: 4 },
    description: '电力基础设施防护，安全+5',
    effects: [{ type: 'safety', value: 5 }],
    target: 'self',
  },
  {
    id: 'DEF036',
    code: 'DEF036',
    name: '卫星通信防护',
    type: 'defense',
    faction: 'defense',
    rarity: 'legendary',
    cost: { compute: 5, funds: 4, information: 4 },
    description: '卫星通信链路防护，安全+5',
    effects: [{ type: 'safety', value: 5 }],
    target: 'self',
  },
  {
    id: 'DEF037',
    code: 'DEF037',
    name: '量子加密',
    type: 'defense',
    faction: 'defense',
    rarity: 'legendary',
    cost: { compute: 6, funds: 3, information: 4 },
    description: '部署量子加密通信，安全+5',
    effects: [{ type: 'safety', value: 5 }],
    target: 'self',
  },
  {
    id: 'DEF038',
    code: 'DEF038',
    name: 'AI威胁检测',
    type: 'defense',
    faction: 'defense',
    rarity: 'legendary',
    cost: { compute: 4, funds: 4, information: 5 },
    description: '使用AI检测威胁，安全+5',
    effects: [{ type: 'safety', value: 5 }],
    target: 'self',
  },
  {
    id: 'DEF039',
    code: 'DEF039',
    name: '区块链防护',
    type: 'defense',
    faction: 'defense',
    rarity: 'legendary',
    cost: { compute: 5, funds: 5, information: 3 },
    description: '区块链网络安全防护，安全+5',
    effects: [{ type: 'safety', value: 5 }],
    target: 'self',
  },

  // T5 传奇卡 (DEF040-047)
  {
    id: 'DEF040',
    code: 'DEF040',
    name: '全球网络防护',
    type: 'defense',
    faction: 'defense',
    rarity: 'legendary',
    cost: { compute: 6, funds: 5, information: 5 },
    description: '全球级网络安全防护，安全+6',
    effects: [{ type: 'safety', value: 6 }],
    target: 'self',
  },
  {
    id: 'DEF041',
    code: 'DEF041',
    name: '国家级安全',
    type: 'defense',
    faction: 'defense',
    rarity: 'legendary',
    cost: { compute: 5, funds: 6, information: 5 },
    description: '国家级网络安全体系，安全+6',
    effects: [{ type: 'safety', value: 6 }],
    target: 'self',
  },
  {
    id: 'DEF042',
    code: 'DEF042',
    name: '军事级防护',
    type: 'defense',
    faction: 'defense',
    rarity: 'legendary',
    cost: { compute: 6, funds: 4, information: 6 },
    description: '军事级网络安全防护，安全+6',
    effects: [{ type: 'safety', value: 6 }],
    target: 'self',
  },
  {
    id: 'DEF043',
    code: 'DEF043',
    name: '太空系统防护',
    type: 'defense',
    faction: 'defense',
    rarity: 'legendary',
    cost: { compute: 6, funds: 5, information: 5 },
    description: '太空系统网络安全防护，安全+6',
    effects: [{ type: 'safety', value: 6 }],
    target: 'self',
  },
  {
    id: 'DEF044',
    code: 'DEF044',
    name: 'AI自主防御',
    type: 'defense',
    faction: 'defense',
    rarity: 'legendary',
    cost: { compute: 6, funds: 5, information: 6 },
    description: '部署自主AI防御系统，安全+6',
    effects: [{ type: 'safety', value: 6 }],
    target: 'self',
  },
  {
    id: 'DEF045',
    code: 'DEF045',
    name: '数字护盾',
    type: 'defense',
    faction: 'defense',
    rarity: 'legendary',
    cost: { compute: 7, funds: 5, information: 5 },
    description: '部署数字护盾系统，安全+7',
    effects: [{ type: 'safety', value: 7 }],
    target: 'self',
  },
  {
    id: 'DEF046',
    code: 'DEF046',
    name: '绝对安全',
    type: 'support',
    faction: 'defense',
    rarity: 'legendary',
    cost: { compute: 5, funds: 5, information: 5 },
    description: '实现绝对安全状态，每回合安全+2',
    effects: [{ type: 'safety_per_turn', value: 2 }],
    target: 'self',
    isAura: true,
  },
  {
    id: 'DEF047',
    code: 'DEF047',
    name: '网络免疫',
    type: 'defense',
    faction: 'defense',
    rarity: 'legendary',
    cost: { compute: 8, funds: 6, information: 6 },
    description: '实现网络免疫状态，直接获得胜利',
    effects: [{ type: 'win', value: 1 }],
    target: 'self',
    winCondition: { type: 'absolute_security', threshold: 100 },
  },
];

// ============================================
// 卡牌数据库导出
// ============================================

export const ALL_CARDS: Card[] = [...ATTACKER_CARDS, ...DEFENDER_CARDS];

export const CARD_DATABASE = {
  attacker: ATTACKER_CARDS,
  defender: DEFENDER_CARDS,
  all: ALL_CARDS,
};

// 按ID查找卡牌
export function getCardById(id: string): Card | undefined {
  return ALL_CARDS.find(card => card.id === id);
}

// 按代码查找卡牌
export function getCardByCode(code: string): Card | undefined {
  return ALL_CARDS.find(card => card.code === code);
}

// 按阵营和稀有度获取卡牌
export function getCardsByFactionAndRarity(faction: CardFaction, rarity: CardRarity): Card[] {
  return ALL_CARDS.filter(card => card.faction === faction && card.rarity === rarity);
}

// 按科技等级获取卡牌 (T0-T5)
export function getCardsByTechLevel(techLevel: number): Card[] {
  const startIndex = techLevel * 8;
  const endIndex = startIndex + 8;
  return [...ATTACKER_CARDS.slice(startIndex, endIndex), ...DEFENDER_CARDS.slice(startIndex, endIndex)];
}

export default CARD_DATABASE;
